#!/bin/sh
# Usage: ./generate-guidelist.sh  >>common-guides.h
# based on generate-cmdlist.sh
echo "/* Automatically generated by $0 */
struct guidename_help {
    char name[16];
    char help[80];
};

static struct guidename_help common_guides[] = {"

sed -n -e 's/^git\([^ 	]*\)[ 	].* guide.*/\1/p' guide-list.txt |
sort |
while read guide
do
     sed -n '
     /^NAME/,/git'"$guide"'/H
     ${
	    x
#	    s/.*git'"$guide"' - \(.*\)/  {"'"$guide"'", N_("\1")},/
	    s/.*git'"$guide"' - \(.*\)/  {"'"$guide"'", "\1"},/
	    p
     }' "Documentation/git$guide.txt"
done
echo "};"

